[
    {"name": "Статични уеб страници","desc" : "Ние предлагаме изработка както на статични, така и на динамични уеб сайтове. Сега ще Ви представим предимствата и недостатъците на динамичните сайтове."},
    {"name": "Динамични уеб страници","desc" : "Ние предлагаме изработка както на статични, така и на динамични уеб сайтове. Сега ще Ви представим предимствата и недостатъците на динамичните сайтове."},
    {"name": "Online shops","desc" : "Have you decided to start an online business? The first step is to make an online shop with a stylish design, functional and attractive. It is priority for us to design a quality online shop for you to help you present your products and services appropriately in order to successfully develop your business."},
    {"name": "Web sites maintenance","desc" : "As everything and sites need maintenance in order to have the site's lever maintained and even increased. Our support includes: uploading new photos and videos, updating texts, adding additional menus and functionalities. We offer both part time support or subsctiption support. Contact us to make the best offer for you and your site."},
    {"name": "Logo design","desc" : "Yes, it all starts with the loge. This is the distinctive and characteristic symbol of your company that carries your message to the customer. We understand that designing a logo is a very important step in every business for its development and success. That is why we strive to fulfill your desire to have the right and unique logo. Trust us."},
    {"name": "Banner design","desc" : "Предпоставка за успешен бизнес е добрата реклама, в частност банерът. Във времето, в което живеем все повече хора прекарват все повече време в Интернет пространството. Това са Вашите потенциални клиенти, които бихте искали да заинтригувате и привлечете към Вашата фирма. Наша цел е да направим за Вас банера, който ще ви представи най- добре, ще бъде интересен  и ще привлече за Вас много клиенти."},
    {"name": "Mobile apps development","desc" : "Mobile apps are software programs designed for mobile devices such as smartphones and tablets. They turn mobile devices into miniature powerful stations for work and entertainment. The purpose of these applications is to cover the range of utility, performance and navigation to entertainment, sports, fitness and almost all other areas. Many organizations have mobile websites and mobile apps. In principle, the difference is in the purpose. The app is typically less in scope than a mobile website, offers more interactivity, and provides more specific information in a format that is easy and intuitive to use on a mobile device. Mobile applications are more expensive to develop than web apps, and as they are platform-specific, launching applications on different platforms is largely meant to start from scratch in terms of design and development. However, they are much faster and are better in terms of features and functionality. Mobile applications are built using specific languages ​​and integrated development environments, depending on the intended platform. Apple devices work on their own iOS operating system so Apple apps are built using Objective-C or Swift and Xcode IDE. Android mobile apps are written in Java and are typically built with Android Studio."},
    {"name": "Facebook page maintenance","desc" : "According to statistics, there are more facebook profiles than people. Nowadays, everyone spends a lot of time on the phones, looking at what his friends have posted. That is why it is important for every business to have a facebook page to promote and maintain contact with its customers. Posting interesting posts will raise the opinion for you for both current and prospective clients. You will surely find new ones. Facebook marketing is one of the most popular and successful promotion and advertising tools at the moment."},
    {"name": "Creation of 360-degrees walk","desc" : "Do you want more and more clients to be intrigued by the apartments, houses, offices, hotels ... from the first glance? You can attract your potential customers in a very promising way. Rely on one of the most impressive and contemporary methods of visualizing your offers, namely 360 degree virtual walks. This will allow you to quickly and easily present the benefits of what you offer."}
]